---
title: "Clumping Hypothesis"
author: "Beau Meche & Robert McKenzie"
date: "2/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

```{r, message=FALSE}
# ignored messages because geom_histogram was complaining about 
# the nature of our discrete data

num_men <- rep(0,14)
num_women <- rep(1,16)

# vector to number table assignment 1-7

class_1 <- seq(1, 7)
class_2 <- seq(7,8)

# a vector to simulate the class composition: 1 = woman

x = c(num_men,num_women)

reps = 10000

# vector to store the sample proportions of women at a given table.

compositions <- vector("numeric", reps)

for (q in 1:reps) {
  
  
      # We randomly select gender order from the x vector and assign them 
      # first to the tables of four and assume that the last two students 
      # will fill the extra 2 seats with the grad students (assuming that
      # they heed Preceptor's insructions)
 
compositions[q] <- data.frame(gender = sample(x, 30),
                     table = c(rep(class_1, 4), 8,8)) %>% 
  group_by(table) %>% 
  
  # how many women at each table in the sample set
  
  summarize(num_women = sum(gender)) %>% 
  
  # assign which tables are / aren't clumped (in this case we delineated
  # on whether the table was homogeneous)
  
  mutate(clumps = ifelse(num_women %in% c(0,4), yes = 1, no = 0)) %>% 
  
  # taking the average gives the % of women at each table
  
  summarise(prop_clumps = mean(clumps))
}

# this is a tricky bit to explain: multiplying the left column in the 
# data frame by 8 because there are 8 tables in play. ggplot required
# a dataframe

compositions <- data.frame(t(as.data.frame(compositions))*8, seq_along(t(as.data.frame(compositions))))

# plot here

mn <- mean(compositions$t.as.data.frame.compositions.....8)
sd = sd(compositions$t.as.data.frame.compositions.....8)


compositions %>% 
  ggplot(aes(x = t.as.data.frame.compositions.....8)) +
  geom_histogram(color = "black", fill = "navy") +
  
  # geom_vlines to mark the interesting stats about out data, 
  # labels are self-explanatory
  
  geom_vline(xintercept = mn, linetype = 1, color = "red") +
  geom_vline(xintercept = c(mn - (1.96*sd), mn + (1.96*sd)), 
             linetype = 2, color = "orange") +
  labs(title = "Testing Seat Randomization in Gov.1006",
       subtitle = "Solid Line Shows Average Clumping Per Class,
Dotted shows 95% Conf.Int. for the mean.",
       x = "Number of Clumped Tables",
       y = "Aggregated Test Results",
       caption = "Manual Bootstrapped Test of Clumping Frequency") +
  scale_x_continuous(breaks = seq(-2,6, by = 1)) +
  theme_bw()

```

We would expect a class of 14 men and 16 women to clump into about `r mn` single gender tables per class meeting, given 4 seats per table with the exception of the last table, which has 2 seats.


